const ORGANIZATION_STATUS = ['AKTIF', 'DITANGGUHKAN'];
export { ORGANIZATION_STATUS };

const ENTITIY_STATUS = ['BUKA', 'TUTUP', 'PEMELIHARAAN'];
export { ENTITIY_STATUS };

const UNIT_TYPE = ['KAMAR', 'MEDIS', 'NON-MEDIS', 'DEPOT'];
export { UNIT_TYPE };

const EMPLOYEE_TYPE = ['DOKTER TETAP', 'DOKTER BERKUNJUNG', 'PERAWAT', 'STAF'];
export { EMPLOYEE_TYPE };

const MARITAL_STATUS = [
  'BELUM MENIKAH',
  'MENIKAH',
  'CERAI MATI',
  'CERAI HIDUP',
];
export { MARITAL_STATUS };

const ENTITY_TYPE = ['GUDANG', 'MEDIS'];
export { ENTITY_TYPE };

const STORAGE_TYPE = [
  'PASOKAN MEDIS',
  'PASOKAN NON - MEDIS ',
  'MAKANAN MENTAH ',
  'MAKANAN OLAHAN ',
  'LAINNYA ',
  'SEMUA ',
];
export { STORAGE_TYPE };

const UNIT_STATUS = ['TERSEDIA', 'PEMELIHARAAN', 'TIDAK TERSEDIA'];
export { UNIT_STATUS };

const RELIGION = [
  'ISLAM',
  'PROTESTAN',
  'KATHOLIK',
  'HINDU',
  'BUDDHA',
  'KHONGHUCU',
];
export { RELIGION };

const RELATION = [
  'BAPAK',
  'IBU',
  'ANAK',
  'SAUDARA KANDUNG',
  'SUAMI',
  'ISTRI',
  'KAKEK',
  'NENEK',
  'KERABAT',
];
export { RELATION };

const APPOINTMENT_METHOD = [
  'WHATSAPP',
  'TELEPON',
  'DI TEMPAT',
  'PERMINTAAN',
  'PIHAK KETIGA',
];
export { APPOINTMENT_METHOD };

const VISIT_TYPE = ['KONSULTASI', 'KONTROL'];
export { VISIT_TYPE };

const APPOINTMENT_STATUS = [
  'BATAL',
  'KADALUARSA',
  'SUDAH REGISTRASI',
  'BELUM REGISTRASI',
];
export { APPOINTMENT_STATUS };

const COB_METHOD = ['PLAFON, CAKUPAN'];
export { COB_METHOD };

const GUARANTOR_TYPE = ['PRIBADI', 'ASURANSI', 'KORPORASI'];
export { GUARANTOR_TYPE };
